#!/usr/bin/python3
import socket
import sys

HOST = '127.0.0.1'
PORT = 8086
BUFFER_SIZE = 1024

def main():
	if len(sys.argv) < 2:
		print('Requires 2 arguments')
		exit()
	
	arguments = sys.argv[1:]
	s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
	try:
		s.connect((HOST, PORT))
	except ConnectionRefusedError:
		print('daga kotowaru')
		exit(1)
	s.send(bytes(' '.join(arguments), 'utf-8'))
	data = s.recv(BUFFER_SIZE)
	s.close()
	
	print(data.decode('utf-8'), end='')

if __name__ == "__main__":
	main()
